### ISSUE TITLE
instance.container is not a function

### ISSUE THREAD

**Issue by vivian-ho** [twokul/ember-cli-bugsnag#41]
I'm trying to upgrade to Ember 2.5 from 2.0 and getting this: TypeError: instance.container is not a function

Sample initializer:
App.initializer({
name: 'appInitializers',
initialize: function(app) {
app.inject('controller', 'test', 'test:main');
app.inject('component', 'test', 'test:main');
app.inject('route', 'test', 'test:main');
app.inject('adapter', 'test', 'test:main');
app.inject('serializer', 'test', 'test:main');
},
});

wondering what I'm doing wrong. Thanks for any help.

**Comment by binhums** [comment]
@vivian-ho hi thanks for raising, appears to be linked to #33. I'll let you know when I've investigated.

**Comment by binhums** [comment]
@vivian-ho Hi Vivian, what version of ember-cli-bugsnag are you using?

It looks like this should not be a problem since 0.1.1 (see #35).

https://github.com/twokul/ember-cli-bugsnag/pull/35

Can you confirm that you are seeing this on v0.1.5, you may need to delete your node_modules folder  and clear your cache with npm.

**Comment by vivian-ho** [comment]
I'm not using ember-cli-bugsnag.  And I deleted node_modules and cleared the cache every time there's a change in the package.json.  If this is not related to ember-cli we can close the case.  Thanks for your investigation.

**Comment by binhums** [comment]
@vivian-ho are you using something else instead?

**Comment by vivian-ho** [comment]
Not sure what caused it.

**Comment by binhums** [comment]
Ok thanks for checking in 👍
